namespace Billing.Api.Features.Invoices;

/// <summary>
/// Lifecycle status of an invoice. Only <see cref="Open"/> is produced by this
/// task; the transition to <see cref="Closed"/> happens in a later task
/// (print/close flow), together with the atomic stock write-off.
/// </summary>
public enum InvoiceStatus
{
    Open,
    Closed,
}

/// <summary>
/// Invoice owned by the Billing service. Numbering is generated by the
/// database (sequence + unique index) so it is unique and sequential
/// regardless of concurrent requests. Items carry a snapshot of the product
/// code/description captured at creation time, so Billing never needs to
/// query Inventory again to render an existing invoice.
/// </summary>
public class Invoice
{
    private readonly List<InvoiceItem> _items = new();

    public int Id { get; private set; }

    public int Number { get; private set; }

    public InvoiceStatus Status { get; private set; }

    public DateTime CreatedAtUtc { get; private set; }

    public IReadOnlyCollection<InvoiceItem> Items => _items.AsReadOnly();

    // Required by EF Core.
    private Invoice()
    {
    }

    private Invoice(IEnumerable<InvoiceItem> items)
    {
        Status = InvoiceStatus.Open;
        CreatedAtUtc = DateTime.UtcNow;
        _items.AddRange(items);
    }

    /// <summary>
    /// Creates a new open invoice with the given items. Throws
    /// <see cref="InvoiceValidationException"/> when there are no items.
    /// The invoice number is assigned by the database on insert.
    /// </summary>
    public static Invoice Create(IReadOnlyCollection<InvoiceItem> items)
    {
        if (items is null || items.Count == 0)
        {
            throw new InvoiceValidationException(["At least one item is required."]);
        }

        return new Invoice(items);
    }
}
